### ISSUE TITLE
Float position or direction

### ISSUE THREAD

**Issue by fedoranvar** [is0n/fm-nvim#11]
Good day to you!

Is it possible for float-window  set position ( [x,y] coordinates of top-left-cornet)  or direction (North, NorthEast, East, ...) ?

Thank you!

**Comment by is0n** [comment]
Seems easy enough! I'll be sure to get this working in no time :)

**Comment by is0n** [comment]
X and Y coordinates can now be set with the following...
```lua
require('fm-nvim').setup{
	ui = {
		float = {
			x         = 0.5,
			y         = 0.5
		}
	}
}
```

**Comment by fedoranvar** [comment]
Great!

Thank you!
