### ISSUE TITLE
Allow directional splits

### ISSUE THREAD

**Issue by rosshadden** [is0n/fm-nvim#14]
I opened another issue with a link to a big vim function in my old vim config. Right above that is this block, unrelated to the other issue:

```vim
" Seamless splits
let g:fzf_action = {
	\ 'ctrl-t': 'tab split',
	\ 'ctrl-k': 'leftabove split',
	\ 'ctrl-j': 'rightbelow split',
	\ 'ctrl-h': 'leftabove vsplit',
	\ 'ctrl-l': 'rightbelow vsplit',
\ }
```

This let me open selected file(s) in fzf in a certain direction. So `<ctrl>+hjkl` would open the file(s) in the expected cardinal direction when inside fzf. I loved this workflow because I don't always know where I want to open files until I'm about to choose them from a finder.

Despite the above confusingly being about fzf which you also support, my question is actually about the file browsers part of the plugin. If I could achieve this with Ranger+vim I believe it would push me into a state of nerd nirvana. I was never quite able to get it working, though I also didn't try incredibly hard at the time. Do you think this is currently possible to implement in user-land? If not, I believe it could become possible if you opened up some of the mappings or internal API functions like `postCreation`.

**Comment by is0n** [comment]
I'm afraid this is something that is most likely not possible. `fm-nvim` opens files by reading `/tmp/fm-nvim` and this file is only created and written to upon the closing of a file manager.

If you want to open multiple files with a single instance of a file manager, then you can select the files you want to open with your file manager's `selection` tool.

With Ranger for example, you could just press `space` while hovering over the files you want to open and there you'll be able to open all of the files with just a single instance of Ranger.
