### ISSUE TITLE
Ctrl-j and Ctrl-k not working when using Broot

### ISSUE THREAD

**Issue by abdallahz3** [is0n/fm-nvim#15]
Hi,
I'm trying to use Broot, but when I click for example Ctrl-j it's does not go one line below, I tried the same with Skim but it's working with Skim, any idea why that is?

**Comment by is0n** [comment]
Do both `Ctrl-j` and `Ctrl-k` work outside of vim? If so, do they both work inside of `:term`?

**Comment by abdallahz3** [comment]
Yes, it is working outside of vim, I noticed that this plugin uses its own config, I changed the config to this
```json
	verbs: [
		{
			key: enter
			execution: ":print_path"
			apply_to: file
		}
		{
			key: ctrl-k
			execution: ":line_up"
		}
		{
			key: ctrl-j
			execution: ":line_down"
		}
	]

```
and it worked!

**Comment by is0n** [comment]
With the latest commit, you can now use your own config file for `Broot`. That way, you can use `ctrl-k` and `ctrl-j` as keybindings.

**Comment by abdallahz3** [comment]
Great, Thanks @is0n
