### ISSUE TITLE
Add shortcuts to open in splits and tabs

### ISSUE THREAD

**Issue by CRAG666** [is0n/fm-nvim#2]
First of all I love your plugin on the other hand I work a lot with splits and tabs and I really miss being able to open the files this way

**Comment by is0n** [comment]
@CRAG666, thanks for checking out the plugin!

To achieve this, you can use the following code...
```lua
require('fm-nvim').setup{
  config =
  {
    edit_cmd = "split"

    -- or...

    edit_cmd = "tabedit"
  }
}
```

This is the only way of opening files in splits and tabs as of right now, however, I'll be sure to update to plugin to support this. How would you like to see this be implemented?
