### ISSUE TITLE
[Feature] Change current directory

### ISSUE THREAD

**Issue by Bekaboo** [is0n/fm-nvim#23]
Is it possible to change current directory using this plugin? It would be much more convenient using file managers to do this intead of using `:cd` command.

**Comment by is0n** [comment]
#18 discusses how to change your cwd with `Xplr` and #4 discusses how to change your cwd with `Ranger`.

Although #18 is specifically for `Xplr`, #4 can be slightly modified to work with a variety of file managers (I've tested it out with `Joshuto` and `Lf`).

If neither methods fit your needs, could you describe what you have in mind?

**Comment by Bekaboo** [comment]
> 

Thanks a lot! That is exactly what I want. Thanks for your great work on this plugin, which make nvim's terminal much more powerful and convenient to integrate other terminal tools with nvim.
