### ISSUE TITLE
Close buffer along with window

### ISSUE THREAD

**Issue by tamton-aquib** [is0n/fm-nvim#24]
In case of floats:
the window is closed, but the buffer is not completely wiped.
![image](https://user-images.githubusercontent.com/77913442/163434817-be75d143-1000-4e4c-8e5d-a29b546099f2.png)

buflist contained this buffer:
![image](https://user-images.githubusercontent.com/77913442/163435197-0f5e4fb3-adcc-4ea3-a353-aee83e391334.png)

<br/>
I tried adding a line to `closeCmd()` inside `createWin()`:

![image](https://user-images.githubusercontent.com/77913442/163435797-534ddd7b-8b0c-4ee1-a240-595886b7279c.png)

and it was temporarily fixed, but i dont know if it breaks anything else 😅

**Comment by is0n** [comment]
It doesn't seem to break anything so I've updated the code to include `vim.api.nvim_buf_delete(M.buf, {force = true})`.

Tested it out with `stabline` and it seems to work. Thanks for pointing this out!
