### ISSUE TITLE
[Feature Request] Allow custom border characters

### ISSUE THREAD

**Issue by Zane-** [is0n/fm-nvim#26]
Being able to specify custom border characters would be nice. Then I could just set a border on the top, or have a rounded border for example.

**Comment by is0n** [comment]
This is already possible. In the case of setting a border on top, you can use the following:
```lua
require("fm-nvim").setup {
  ui = {
    float = {
      border = { "╭", "─", "╮", "", "", "", "", "" },
    }
  }
}
```
