### ISSUE TITLE
Update CWD on file manager close

### ISSUE THREAD

**Issue by jakobkhansen** [is0n/fm-nvim#4]
Hi, great plugin, looking forward to using it.

One feature I would like is to be able to navigate to a folder and exit, with the CWD updated to that folder. Example usage would be navigate to a project root, exit and have CWD in that folder.

**Comment by is0n** [comment]
You can actually do this with a vim setting called `autochdir`. You can set this by using the following in your `init.lua`...
```lua
vim.opt.autochdir = true
```
Is this what you had in mind?

**Comment by is0n** [comment]
Sorry for the late response but after the latest commit, you might be able to do this.

The latest commit allows you to run functions upon exiting the floating window. This can be seen on the [README](https://github.com/is0n/fm-nvim#qa).

If you were using [Lf](https://github.com/gokcehan/lf) for example, you could change the command to use `-last-dir-path` which would write the file manager's last directory path to a specified file. Then using `on_close` and your function, you could read that file and then `cd` there.

The code would be something like...
```lua
local function updateCWD()
	-- some code that checks /tmp/cwd
end

require('fm-nvim').setup{
	cmds = {
		lf_cmd = "lf -last-dir-path /tmp/cwd"
	}
	on_close = { updateCWD }
}
```

I think the issue should be resolved but please LMK if there's anything missing :)

**Comment by jakobkhansen** [comment]
Great, I went with that idea and it worked! If anyone wants to do something similar, this is what I ended up with:

```lua
on_close = {
  function()
            local file = io.open("/tmp/ranger_dir", "r")
  
            io.input(file)
  
  
            local dir = io.read()
            command('cd ' .. dir)
  end,
},
```

and a mapping to this command (Ranger):

```vimscript
<CMD>Ranger --choosedir="/tmp/ranger_dir"<CR>
```
