### ISSUE TITLE
Support broot?

### ISSUE THREAD

**Issue by IndianBoy42** [is0n/fm-nvim#5]
https://github.com/Canop/broot

Would it be possible to add support for broot in this plugin?

**Comment by is0n** [comment]
> Would it be possible to add support for broot in this plugin?

I'm not sure as I've never used broot before. How might you suggest I accomplish this?

**Comment by IndianBoy42** [comment]
So actually I think I could implement this if `createWin` and `setMappings` were public. 

broot has `--outcmd` which is similar to what you use with the other file managers, although it outputs a whole command, not just the filename of the selected file/dir. So I would need a custom on_close to parse that somehow

**Comment by is0n** [comment]
> So actually I think I could implement this if createWin and setMappings were public

The most recent commit should have done this.

For future reference, you could also clone the repo and include it in your list of plugins. The following should work assuming you use packer...
```
$ git clone https://github.com/is0n/fm-nvim ~/fm-nvim
```
```lua
use {'~/fm-nvim'}
```

With that, you wouldn't need to have those functions be public.

Hope this helps! 😄

**Comment by is0n** [comment]
After some tinkering around, I've found one possible way of supporting broot.

It's by using...
```
$ broot --out /tmp/fm-nvim
```

Using the following will use `/tmp/fm-nvim` as a temp file. The only problem is that if you now want to open a file, you have to select it and do `:print_path` in broot. Do you know how we can map `Return/Enter` to `:print_path` in broot? I imagine it's by using `--conf`.

The following resources may help...
* [vim-floaterm](https://github.com/voldikss/vim-floaterm/blob/master/autoload/floaterm/wrapper/broot.vim#L12-L23)
* [broot.vim](https://github.com/lstwn/broot.vim/blob/master/plugin/broot.vim#L23-L28)
* [docs](https://dystroy.org/broot/conf_verbs)

If you would like to try it out, use the following in neovim...
```
:lua require('fm-nvim').createWin("broot --out /tmp/fm-nvim")
```
and then type...
```
:print_path
```
in broot once you have selected a file.

**Comment by is0n** [comment]
Latest commit fixes the issue. LMK if there's anything that's missing or that is buggy :)
