### ISSUE TITLE
Cannot see image preview

### ISSUE THREAD

**Issue by RaZ0rr-Two** [is0n/fm-nvim#6]
I am using vifm with image previews with the help of two scripts vifmimg (used for preview) and vifmrun (used to run vifm). They are documented here [cirala/vifmimg](https://github.com/cirala/vifmimg). But I am not able to get previews while using fm-nvim. But [floaterm](https://github.com/voldikss/vim-floaterm) does show a preview. 

I have shown the problem in this gif

![Peek 2021-11-13 14-52](https://user-images.githubusercontent.com/84911063/141614449-80856068-0d8f-4a16-a0d9-6ca2ce966ca3.gif)

**Comment by is0n** [comment]
By looking at your `fm-nvim` settings, I can see that the way you are changing the `vifm_cmd` differs from the actual config. This is my fault as README didn't tell you this.

Add the following to your config...
```lua
require('fm-nvim').setup{
        -- other settings
	cmds = {
		vifm_cmd   = "~/.local/bin/vifmrun",
	}
        -- other settings
}
```

**Comment by RaZ0rr-Two** [comment]
Thank you that fixed the issue.

Also, there's two more typos (maybe, I'm not that good at lua). One comma after `twf_cmd `and after `cmds` 

Also, I have one another issue (very small) that I will make new issue for
