### ISSUE TITLE
Closing command and closing message

### ISSUE THREAD

**Issue by RaZ0rr-Two** [is0n/fm-nvim#7]
I am getting this message when I close vifm

```
...hare/nvim/site/pack/packer/start/fm-nvim/lua/fm-nvim.lua:43: attempt to concatenate a nil value                            
stack traceback:
^I...hare/nvim/site/pack/packer/start/fm-nvim/lua/fm-nvim.lua:43: in function <...hare/nvim/site/pack/packer/start/fm-nvim/lua/fm-nvim.l
ua:39>
```
Can be seen here

![Peek 2021-11-13 14-52](https://user-images.githubusercontent.com/84911063/141649636-e044b052-f228-469c-bb96-f87daa950591.gif)

Also, I cannot close with `<Esc>` as it sends `q` which is not my close command. 

Can we have an option to define `<Esc>` ? Like if I want to send `qa` or  `Q` instead ?

**Comment by is0n** [comment]
Fixed the issue with `<ESC>` and I'll be sure to allow the user to define it.

As for the closing message, I can't say what could be causing this as I don't receive any type of message while I use it. Try updating and tell me if the message still shows.

**Comment by RaZ0rr-Two** [comment]
I tried with the update but the message is still there.

I will try with minimal rc file and report back.

**Comment by is0n** [comment]
Here's my config file in case you need it. It uses most of the defaults.

```lua
require('fm-nvim').setup{
	border   = "rounded",
	cmds = {
		fzf_cmd  = "fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'",
		skim_cmd = "sk --preview 'bat --style=numbers --color=always --line-range :500 {}'",
	},
}
```

The latest commit also lets the user define `<ESC>` in `mappings`.
```lua
mappings = {
	vert_split  = "<C-v>",
	horz_split  = "<C-h>",
	tabedit     = "<C-t>",
	edit        = "<C-e>",
	ESC         = "<ESC>"
}
```
