### ISSUE TITLE
Unable to open multiple selected files in Vifm

### ISSUE THREAD

**Issue by sQVe** [is0n/fm-nvim#9]
👋🏼,

Cheers for a great plugin.

Like the title says: it's currently not possible to select multiple files in `vifm` and open them with `fm-nvim`.

Steps to reproduce:
- Execute `:Vifm`.
- Press `V` and select multiple files.
- Press `CR`.
- It only opens the first file and not all files.

**Comment by is0n** [comment]
The most recent commit should have fixed this issue.
